# Site
name: 'Quality Times'
description: 'You can find quality articles about software testing and test automation'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'qualitytimes-tech'
email: 'qualitytimestechs@gmail.com'
mailchimp-list: 'https://tech.us7.list-manage.com/subscribe/post?u=b2e1fe1f9d06371e2cba52f4d&amp;id=43b8bef90e'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    philip:
      name:           Philip
      site:           https://philipkurian.github.io
      avatar:         assets/images/avatar1.jpg
      bio:            "Test Automation Architect/ Developer/ Lead"
      email:          philipkurian.nz@gmail.com
      linkedIn:        https://www.linkedin.com/in/kurianphilipk/

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]